### ISSUE TITLE
Automated Setup for Database testing

### ISSUE THREAD

**Issue by lakooi** [aalto-grades/base-repository#114] opened 2023-01-11 10:14 UTC
As a backend developer, I want to be able to run unit  tests easily against a database locally, so that I can test my work 

- [ ] Documentation for running configuration locally
- [ ] Github Action Configuration  for docker-compose
- [ ] Docker-compose configuration for running tests with database
- [ ] #69

**Comment by no-comma** [comment] 2023-01-11 10:59
Duplicate of #98

**Closed by no-comma** 2023-01-11 10:59 UTC
